### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by livartly** [livartly/StressedOutInSpace#5]
Displays upon game load. Contains play button and credits button. Play button starts game, credits button redirects to credits page

- [x] Create main menu graphic

- [x] Create start button

- [x] Create credits button

- [x] Implement start for play button

- [x] Implement redirect for credits button

**Comment by Ranner198** [comment]
Added basic buttons

**Comment by livartly** [comment]
Replaced with basic with final UI buttons
